AllCops:
  Exclude:
    - 'lib/middleman/apps/rack_contrib.rb'
    - 'tmp/aruba'

Metrics/ClassLength:
  Exclude:
    - 'lib/middleman/apps/extension.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

