Naming/FileName:
  Exclude:
    - 'lib/middleman-apps.rb'

Metrics/ClassLength:
  Exclude:
    - 'lib/middleman-apps/extension.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

